name: Compile Using Nuitka

on:
  workflow_dispatch:
  
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'

      - name: Run prep.sh
        run: chmod +x prep.sh && ./prep.sh

      - name: Run build script
        run: python compile.py

      - name: Run post-compile script
        run: chmod +x clean.sh && ./clean.sh
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit generated file
        run: |
          git add .
          git commit -m "Automated build by Github Actions" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

