name: Compile Using Nuitka (glibc 2.33)

on:
  workflow_dispatch:

  push:
    tags:
      - '*'
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build inside Docker with glibc 2.33
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app debian:bullseye bash -c "
            apt update &&
            apt install -y curl software-properties-common gcc g++ git sudo wget make zlib1g-dev libffi-dev &&
            wget https://www.python.org/ftp/python/3.12.2/Python-3.12.2.tgz &&
            tar -xzf Python-3.12.2.tgz &&
            cd Python-3.12.2 &&
            ./configure --enable-optimizations &&
            make -j$(nproc) &&
            make altinstall &&
            cd /app &&
            ln -s /usr/local/bin/python3.12 /usr/bin/python3 &&
            ln -s /usr/local/bin/pip3.12 /usr/bin/pip3 &&
            python3 --version &&
            pip3 install --upgrade pip &&
            pip3 install nuitka &&
            chmod +x prep.sh clean.sh &&
            ./prep.sh &&
            python3 compile.py &&
            ./clean.sh
          "

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit generated file
        run: |
          git add .
          git commit -m "Automated build by Github Actions" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
