name: Compile Using Nuitka (glibc 2.33)

on:
  workflow_dispatch:

  push:
    tags:
      - '*'
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build inside Docker with glibc 2.33
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app python:3.10-bullseye bash -c "
            apt update &&
            apt install -y curl gcc g++ git &&
            pip install nuitka &&
            chmod +x prep.sh clean.sh &&
            ./prep.sh &&
            python compile.py &&
            ./clean.sh
          "

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit generated file
        run: |
          git add .
          git commit -m "Automated build by Github Actions" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
