name: Compile Using Nuitka (glibc 2.33)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., v1.0.1)'
        required: true
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build inside Docker with glibc 2.33
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app python:3.10-bullseye bash -c "
            apt update &&
            apt install -y curl gcc g++ git sudo &&
            pip install nuitka &&
            chmod +x prep.sh clean.sh &&
            ./prep.sh &&
            python compile.py &&
            ./clean.sh
          "

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit generated file
        run: |
          git add .
          git commit -m "Automated build by Github Actions" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}

      - name: Create Git Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
          TAG=${{ github.event.inputs.version }}
          git fetch --tags
          if git rev-parse "refs/tags/$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping tag creation."
          else
            git tag "$TAG"
            git push origin "$TAG"
          fi

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: ./bin/*.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
